In [7]:
import numpy as np
import pandas as pd
import sklearn 

In [ ]:
def run():
    #     # my_dict = {keys: keys**3 for keys in range(1, 101) if keys % 3 != 0}
    #     # print(my_dict)

    my_dict = {keys: keys**(1/2) for keys in range(1, 101) if keys % 3 != 0}
    print(my_dict)


if __name__ == ('__main__'):
    run()


NUMPY

Biblioteca de Python comúnmente usada en la ciencias de datos y aprendizaje automático (Machine Learning). Proporciona una estructura de datos de matriz que tiene diversos beneficios sobre las listas regulares.

In [45]:
array = np.array([3, 4, 5, 6, 7, 8, 9, 10])
array_2 = np.array([[3, 4, 5], [5, 7, 3]])
array_3 = np.array([[3, 4, 5], [5, 7, 3], [7, 5, 3]])
print(f'''arreglo unidimensional: 
{array}
elementos: {len(array)}
suma de elementos: {np.sum(array)}
número máximo del arreglo: {np.max(array)}

arreglo bidimensional: 
{array_2}
elementos: {len(array_2)}
suma de elementos: {np.sum(array_2)}
número máximo del arreglo: {np.max(array_2)}


arreglo tridimencionl:
{array_3}
elementos: {len(array_3)}
suma de elementos: {np.sum(array_3)}
número máximo del arreglo: {np.max(array_3)}
 ''')


arreglo unidimensional: 
[ 3  4  5  6  7  8  9 10]
elementos: 8
suma de elementos: 52
número máximo del arreglo: 10

arreglo bidimensional: 
[[3 4 5]
 [5 7 3]]
elementos: 2
suma de elementos: 27
número máximo del arreglo: 7


arreglo tridimencionl:
[[3 4 5]
 [5 7 3]
 [7 5 3]]
elementos: 3
suma de elementos: 42
número máximo del arreglo: 7
 


In [55]:
cero = np.zeros(4)
uno = np.ones(4)
cero, uno

(array([0., 0., 0., 0.]), array([1., 1., 1., 1.]))

In [60]:
type(uno)

numpy.ndarray

In [74]:
np.sort(array_3)

array([[3, 4, 5],
       [3, 5, 7],
       [3, 5, 7]])

In [78]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
np.arange(4, 14)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [80]:
np.arange(5, 50, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [86]:
np.full((2, 3), 5)

array([[5, 5, 5],
       [5, 5, 5]])

PANDAS

Pandas es una herramienta de manipulación de datos de alto nivel, es construido con la biblioteca de Numpy. Su estructura de datos más importante y clave en la manipulación de la información es DataFrame, el cuál nos va a permitir almacenar y manejar datos tabulados observaciones (filas) y variables (columnas).



In [87]:
pd.Series([5, 3, 6, 3, 6])

0    5
1    3
2    6
3    3
4    6
dtype: int64

In [90]:
pd.DataFrame( ['Hola', 'Mundo', 'Robotico'] )

0
0      Hola
1     Mundo
2  Robotico

In [92]:
data = {'Nombre':['juan', 'Pilo', 'Loop', 'Ana'],
'Edad':[4, 35, 63, 23],
'País': ['MX', 'EC', 'BRA', 'CO']}
df = pd.DataFrame(data)
df


Nombre  Edad País
0   juan     4   MX
1   Pilo    35   EC
2   Loop    63  BRA
3    Ana    23   CO

In [95]:
data = pd.read_csv('./CSV/canciones-2018.csv')

In [97]:
data.head(3)

id                        name       artists  \
0  6DCZcSspjsKoFjzjrWoCd                  God's Plan         Drake   
1  3ee8Jmje8o58CHK66QrVC                        SAD!  XXXTENTACION   
2  0e7ipj03S05BNilyu5bRz  rockstar (feat. 21 Savage)   Post Malone   

   danceability  energy  key  loudness  mode  speechiness  acousticness  \
0         0.754   0.449  7.0    -9.211   1.0       0.1090        0.0332   
1         0.740   0.613  8.0    -4.880   1.0       0.1450        0.2580   
2         0.587   0.535  5.0    -6.090   0.0       0.0898        0.1170   

   instrumentalness  liveness  valence    tempo  duration_ms  time_signature  
0          0.000083     0.552    0.357   77.169     198973.0             4.0  
1          0.003720     0.123    0.473   75.023     166606.0             4.0  
2          0.000066     0.131    0.140  159.847     218147.0             4.0

In [98]:
data.columns

Index(['id', 'name', 'artists', 'danceability', 'energy', 'key', 'loudness',
       'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo', 'duration_ms', 'time_signature'],
      dtype='object')

In [99]:
data.tail(5)

id                               name       artists  \
95  630sXRhIcfwr2e4RdNtjK                  Rewrite The Stars     Zac Efron   
96  2xmrfQpmS2iJExTlklLoA  I Miss You (feat. Julia Michaels)  Clean Bandit   
97  5WvAo7DNuPRmk4APhdPzi                         No Brainer     DJ Khaled   
98  1j4kHkkpqZRBwE0A4CN4Y        Dusk Till Dawn - Radio Edit          ZAYN   
99  3EPXxR3ImUwfayaurPi3c                         Be Alright    Dean Lewis   

    danceability  energy   key  loudness  mode  speechiness  acousticness  \
95         0.684   0.619  10.0    -7.005   1.0       0.0386        0.0716   
96         0.638   0.658   3.0    -6.318   1.0       0.0456        0.2450   
97         0.552   0.760   0.0    -4.706   1.0       0.3420        0.0733   
98         0.258   0.437  11.0    -6.593   0.0       0.0390        0.1010   
99         0.553   0.586  11.0    -6.319   1.0       0.0362        0.6970   

    instrumentalness  liveness  valence    tempo  duration_ms  time_signature  
95          0.000000    0.1220   0.2840  125.046     217440.0             4.0  
96          0.000004    0.0919   0.3300  105.076     205748.0             4.0  
97          0.000000    0.0865   0.6390  135.702     260000.0             5.0  
98          0.000001    0.1060   0.0967  180.043     239000.0             4.0  
99          0.000000    0.0813   0.4430  126.684     196373.0             4.0

In [100]:
data.shape

(100, 16)

In [102]:
data.id

0     6DCZcSspjsKoFjzjrWoCd
1     3ee8Jmje8o58CHK66QrVC
2     0e7ipj03S05BNilyu5bRz
3     3swc6WTsr7rl9DqQKQA55
4     2G7V7zsVDxg1yRsu7Ew9R
              ...          
95    630sXRhIcfwr2e4RdNtjK
96    2xmrfQpmS2iJExTlklLoA
97    5WvAo7DNuPRmk4APhdPzi
98    1j4kHkkpqZRBwE0A4CN4Y
99    3EPXxR3ImUwfayaurPi3c
Name: id, Length: 100, dtype: object

In [103]:
data['name'].describe()

count            100
unique           100
top       God's Plan
freq               1
Name: name, dtype: object

In [104]:
data.sort_index(axis = 0, ascending = False)



id                               name       artists  \
99  3EPXxR3ImUwfayaurPi3c                         Be Alright    Dean Lewis   
98  1j4kHkkpqZRBwE0A4CN4Y        Dusk Till Dawn - Radio Edit          ZAYN   
97  5WvAo7DNuPRmk4APhdPzi                         No Brainer     DJ Khaled   
96  2xmrfQpmS2iJExTlklLoA  I Miss You (feat. Julia Michaels)  Clean Bandit   
95  630sXRhIcfwr2e4RdNtjK                  Rewrite The Stars     Zac Efron   
..                    ...                                ...           ...   
4   2G7V7zsVDxg1yRsu7Ew9R                     In My Feelings         Drake   
3   3swc6WTsr7rl9DqQKQA55       Psycho (feat. Ty Dolla $ign)   Post Malone   
2   0e7ipj03S05BNilyu5bRz         rockstar (feat. 21 Savage)   Post Malone   
1   3ee8Jmje8o58CHK66QrVC                               SAD!  XXXTENTACION   
0   6DCZcSspjsKoFjzjrWoCd                         God's Plan         Drake   

    danceability  energy   key  loudness  mode  speechiness  acousticness  \
99         0.553   0.586  11.0    -6.319   1.0       0.0362        0.6970   
98         0.258   0.437  11.0    -6.593   0.0       0.0390        0.1010   
97         0.552   0.760   0.0    -4.706   1.0       0.3420        0.0733   
96         0.638   0.658   3.0    -6.318   1.0       0.0456        0.2450   
95         0.684   0.619  10.0    -7.005   1.0       0.0386        0.0716   
..           ...     ...   ...       ...   ...          ...           ...   
4          0.835   0.626   1.0    -5.833   1.0       0.1250        0.0589   
3          0.739   0.559   8.0    -8.011   1.0       0.1170        0.5800   
2          0.587   0.535   5.0    -6.090   0.0       0.0898        0.1170   
1          0.740   0.613   8.0    -4.880   1.0       0.1450        0.2580   
0          0.754   0.449   7.0    -9.211   1.0       0.1090        0.0332   

    instrumentalness  liveness  valence    tempo  duration_ms  time_signature  
99          0.000000    0.0813   0.4430  126.684     196373.0             4.0  
98          0.000001    0.1060   0.0967  180.043     239000.0             4.0  
97          0.000000    0.0865   0.6390  135.702     260000.0             5.0  
96          0.000004    0.0919   0.3300  105.076     205748.0             4.0  
95          0.000000    0.1220   0.2840  125.046     217440.0             4.0  
..               ...       ...      ...      ...          ...             ...  
4           0.000060    0.3960   0.3500   91.030     217925.0             4.0  
3           0.000000    0.1120   0.4390  140.124     221440.0             4.0  
2           0.000066    0.1310   0.1400  159.847     218147.0             4.0  
1           0.003720    0.1230   0.4730   75.023     166606.0             4.0  
0           0.000083    0.5520   0.3570   77.169     198973.0             4.0  

[100 rows x 16 columns]

SCIKIT LEARN

Scikit Learn es una biblioteca de Python que está conformada por algoritmos de clasificación, regresión, reducción de la dimensionalidad y clustering. Es una biblioteca clave en la aplicación de algoritmos de Machine Learning, tiene los métodos básicos para llamar un algoritmo, dividir los datos en entrenamiento y prueba, entrenarlo, predecir y ponerlo a prueba.

Importar biblioteca:

from sklearn import [modulo]

División del conjunto de datos para entrenamiento y pruebas:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

Entrenar modelo:

[modelo].fit(X_train, y_train)

Predicción del modelo:

Y_pred = [modelo].predict(X_test)

Matriz de confusión:

metrics.confusion_matrix(y_test, y_pred)

Calcular la exactitud:

metrics.accuracy_score(y_test, y_pred)